// Package scripts 生成项目根目录的 star-yi 命令。
//
// 脚本本身不带逻辑，只把当前项目根交给本机的 star-yi-cli。查找顺序：
// 环境变量 STAR_YI_CLI → 创建器记下的 cli-path.txt → PATH 里的 star-yi-cli。
package scripts

import (
	"os"
	"path/filepath"
	"strings"
)

const (
	CmdName = "star-yi.cmd"
	ShName  = "star-yi.sh"
)

const cmdScript = `@echo off
rem Star-Yi project command. Generated by star-yi-cli.
rem   star-yi.cmd                 menu
rem   star-yi.cmd add-app         add a module
rem   star-yi.cmd remove-app      remove a module
rem   star-yi.cmd list-apps       list modules
setlocal
for /f "tokens=2 delims=:." %%c in ('chcp') do set "STAR_YI_OLDCP=%%c"
chcp 65001 >nul

set "STAR_YI_ROOT=%~dp0"
if "%STAR_YI_ROOT:~-1%"=="\" set "STAR_YI_ROOT=%STAR_YI_ROOT:~0,-1%"

set "STAR_YI_EXE="
if defined STAR_YI_CLI set "STAR_YI_EXE=%STAR_YI_CLI%"
if not defined STAR_YI_EXE if exist "%APPDATA%\star-yi-cli\cli-path.txt" set /p STAR_YI_EXE=<"%APPDATA%\star-yi-cli\cli-path.txt"
if defined STAR_YI_EXE if not defined STAR_YI_CLI if not exist "%STAR_YI_EXE%" set "STAR_YI_EXE="
if not defined STAR_YI_EXE (
  where star-yi-cli >nul 2>nul && set "STAR_YI_EXE=star-yi-cli"
)
if not defined STAR_YI_EXE (
  echo star-yi-cli not found. Run star-yi-cli.exe once, add it to PATH, or set STAR_YI_CLI.
  set "STAR_YI_EC=1"
  goto done
)

"%STAR_YI_EXE%" app %* --project "%STAR_YI_ROOT%"
set "STAR_YI_EC=%ERRORLEVEL%"

:done
if defined STAR_YI_OLDCP chcp %STAR_YI_OLDCP: =% >nul
endlocal & exit /b %STAR_YI_EC%
`

const shScript = `#!/usr/bin/env sh
# Star-Yi 项目命令，由 star-yi-cli 生成。
#   ./star-yi.sh                 菜单
#   ./star-yi.sh add-app         添加应用模块
#   ./star-yi.sh remove-app      删除应用模块
#   ./star-yi.sh list-apps       查看应用模块
set -e
ROOT="$(cd "$(dirname "$0")" && pwd)"

CLI="${STAR_YI_CLI:-}"
if [ -z "$CLI" ]; then
  case "$(uname -s)" in
    Darwin) CFG="$HOME/Library/Application Support/star-yi-cli" ;;
    MINGW*|MSYS*|CYGWIN*) CFG="${APPDATA:-$HOME/AppData/Roaming}/star-yi-cli" ;;
    *) CFG="${XDG_CONFIG_HOME:-$HOME/.config}/star-yi-cli" ;;
  esac
  if [ -f "$CFG/cli-path.txt" ]; then
    CLI="$(cat "$CFG/cli-path.txt")"
    [ -e "$CLI" ] || CLI=""
  fi
fi
if [ -z "$CLI" ]; then
  if command -v star-yi-cli >/dev/null 2>&1; then
    CLI="star-yi-cli"
  else
    echo "没有找到 star-yi-cli：先运行一次创建器，或把它加入 PATH，或设置 STAR_YI_CLI。" >&2
    exit 1
  fi
fi

exec "$CLI" app "$@" --project "$ROOT"
`

// Write 在项目根写入 star-yi.cmd 和 star-yi.sh，返回写入的文件。
func Write(root string) ([]string, error) {
	cmdPath := filepath.Join(root, CmdName)
	shPath := filepath.Join(root, ShName)
	cmd := strings.ReplaceAll(strings.ReplaceAll(cmdScript, "\r\n", "\n"), "\n", "\r\n")
	if err := os.WriteFile(cmdPath, []byte(cmd), 0o644); err != nil {
		return nil, err
	}
	if err := os.WriteFile(shPath, []byte(shScript), 0o755); err != nil {
		return nil, err
	}
	return []string{cmdPath, shPath}, nil
}
